id: P006844
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG24915
  title: འཛམ་གླིང་བྱིས་སྒྲུང་གྲགས་ཅན།
  author: ''
  volumes:
    c64d71da1a0242849eccf9ef8753fca6:
      image_group_id: I1KG24917
      title: ''
      volume_number: 1
      total_pages: 358
    0e8f048abcc947b99228cc377fe76a65:
      image_group_id: I1KG24918
      title: ''
      volume_number: 2
      total_pages: 358
    ced8ce6ab6bb4119a1e3bd8d26d43173:
      image_group_id: I1KG24919
      title: ''
      volume_number: 3
      total_pages: 380
    8713f63765d448d89d344bd587b83f81:
      image_group_id: I1KG24920
      title: ''
      volume_number: 4
      total_pages: 390
    83c45d6bfa9c4061ab22c9901b82741f:
      image_group_id: I1KG24921
      title: ''
      volume_number: 5
      total_pages: 374
    fa094a63373a4cdcaacf9c8649440b7e:
      image_group_id: I1KG24922
      title: ''
      volume_number: 6
      total_pages: 374
    f7dbe0efab974291a7bc909a8099d3d9:
      image_group_id: I1KG24923
      title: ''
      volume_number: 7
      total_pages: 340
    1640eb03c765483fa1de9fc2c61e5c56:
      image_group_id: I1KG24924
      title: ''
      volume_number: 8
      total_pages: 372
