id: I449F59C8
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T20:28:48+00:00'
last_modified: '2022-06-08T07:16:00.223986+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG24915
  title: འཛམ་གླིང་བྱིས་སྒྲུང་གྲགས་ཅན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    '4778':
      image_group_id: I1KG24917
      title: ''
      total_pages: 358
      order: 1
      base_file: 4778.txt
    330F:
      image_group_id: I1KG24918
      title: ''
      total_pages: 358
      order: 2
      base_file: 330F.txt
    B17C:
      image_group_id: I1KG24919
      title: ''
      total_pages: 380
      order: 3
      base_file: B17C.txt
    6C2B:
      image_group_id: I1KG24920
      title: ''
      total_pages: 390
      order: 4
      base_file: 6C2B.txt
    '8429':
      image_group_id: I1KG24921
      title: ''
      total_pages: 374
      order: 5
      base_file: 8429.txt
    '2486':
      image_group_id: I1KG24922
      title: ''
      total_pages: 374
      order: 6
      base_file: 2486.txt
    45A4:
      image_group_id: I1KG24923
      title: ''
      total_pages: 340
      order: 7
      base_file: 45A4.txt
    EED8:
      image_group_id: I1KG24924
      title: ''
      total_pages: 372
      order: 8
      base_file: EED8.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
